
Get http://localhost:3000/movies/

###

delete http://localhost:3000/movies/1
###
Get http://localhost:3000/movies/1

###
get http://localhost:3000/movies/search?year=2000


###
post http://localhost:3000/movies/
Content-Type: application/json

{
    "title":"내부자",
    "year":123,
    "genres":"ewf"
}

###
PATCH http://localhost:3000/movies/2
Content-Type: application/json

{
    "title":"Tenet",
    "year":"Nolan",
    "genres":"ee"
}