
http://localhost:3000/movies/1


###
post http://localhost:3000/movies/
Content-Type: application/json

{
    "name": "Tenet",
    "director":"Nolan"
}

###
PATCH http://localhost:3000/movies/2
Content-Type: application/json

{
    "name":"Tenet",
    "director":"Nolan",
    "rating":4.5
}